### ISSUE TITLE
.env ignored

### ISSUE THREAD

**Issue by FelixWeis** [satsnames/satsnamesapi#2]
Created a dotevn file with `DATABASE_URL` but config not used when running `pnpm dev`

**Comment by tcphandshake** [comment]
can you share the exact error message you are facing?

**Comment by jeffdoms** [comment]
Also trying to run an indexer and hitting same issue. 

The problem itself is that is not reading the variable as expected from the readme.md specifications as it says to create this variable 

`DATABASE_URL="postgresql://localhost:5432/sats-api-dev"`
 
and the error is that the variable is inexistent

**Comment by BowTiedDeployer** [comment]
The solution is to delete the `pnpm-lock.yaml` file and then run `pnpm install` and `pnpm dev`.
