### ISSUE TITLE
Running a local instance for the postgress db on localhost:5432/sats-api-dev

### ISSUE THREAD

**Issue by BowTiedDeployer** [satsnames/satsnamesapi#5]
When running I need to have a postgress database locally. 

There isn't specified on the docs how to create an instance of the DB.

```bash
PrismaClientInitializationError: Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`
```

**Comment by sats-wizard** [comment]
Here are ways to install postgres, ie

for mac: https://formulae.brew.sh/formula/postgresql@14
for windows: https://www.postgresql.org/download/windows/
for linux: https://www.postgresql.org/download/

then i believe if you run `pnpm prisma migrate dev` (just added to readme) i believe it creates the database for you

**Comment by BowTiedDeployer** [comment]
Thanks, tried both with brew and dmg file, but when running `pnpm prisma migrate dev` I get 

```
❯ pnpm prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "sats-api-dev", schema "public" at "localhost:5432"

Error: P1010: User `` was denied access on the database `sats-api-dev.public`
```

Should username and password be provided in the .env config as well?
